language: python

sudo: true

services:
  - mysql

python:
  - "2.7"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  #- gem install s3
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"



before_script:

  - "chmod 777 ~/.ssh/known_hosts"
  - "echo $KNOWN_HOSTS >> ~/.ssh/id_rsa.pub"
  - "echo $SSH_KEY > /home/travis/.ssh/key"
  - "cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "today=$(date +%d.%m.%Y)"
  #- "find / -type f -perm /6000 -exec stat -c "%A %a %n" {} \"

  - sudo apt-get install apache2
  - sudo apt-get install php5 php-pear php5-mysql
  - sudo service apache2 restart
  - ls -l


  - cd ~
  - ls -l
  - cd ..
  #- cd build
  - ls -l
  - cd ..
  - ls -l
  - cd var
  - ls -l
  - cd www
  - ls -l
  #- cd html
  #- ls -l
  - sudo git clone -b testlink_1_9 https://github.com/TestLinkOpenSourceTRMS/testlink-code.git
  - cd testlink-code
  - sudo git checkout 1.9.14
  #- ls -l
  - cd ..
  #- ls -l
  - sed -e 's/\s\+/\n/g' ~/.ssh/key > ~/.ssh/key1
  - echo -----BEGIN RSA PRIVATE KEY----- > /home/travis/.ssh/id_rsa
  - cat ~/.ssh/key1 >> ~/.ssh/id_rsa
  - echo -----END RSA PRIVATE KEY----- >> /home/travis/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host testlab.tesena.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo " StrictHostKeyChecking no" >> ~/.ssh/config
  - scp -v -i ~/.ssh/id_rsa ubuntu@testlab.tesena.com:/home/ubuntu/travisconfigfile/config_db.inc.php /home/travis/config_db.inc.php
  - sudo cp /home/travis/config_db.inc.php /var/www/testlink-code/config_db.inc.php
  - ls -l
  - cd testlink-code
  - ls -l

  - sudo chown -R www-data:www-data ../testlink-code

  #- sudo chmod 777 /home/travis/build/marcel-veselka/testlink-qa-robot/testlink-code/config_db.inc
  #- mysql -u root -p$DB_PSWD -e 'CREATE DATABASE testlink_qa CHARACTER SET utf8 COLLATE utf8_general_ci;';
  #- mysql -u root -p$DB_PSWD testlink_qa < install/sql/mysql/testlink_create_tables.sql;
  #- mysql -u root -p$DB_PSWD testlink_qa < install/sql/mysql/testlink_create_default_data.sql
  #- SET PASSWORD FOR root@localhost=PASSWORD('');
  - mysql -u root -e 'CREATE DATABASE testlink_qa CHARACTER SET utf8 COLLATE utf8_general_ci;';
  - mysql -u root testlink_qa < install/sql/mysql/testlink_create_tables.sql;
  - mysql -u root testlink_qa < install/sql/mysql/testlink_create_default_data.sql
  #- sudo dpkg-reconfigure mysql-server-5.5
  #- SET PASSWORD FOR root@localhost=PASSWORD('');


  - ls -l
  - sudo rm -f -r install
  - cd ..
  - ifconfig eth0 | grep inet | awk '{ print $2 }'
  - sudo hostname -I
  - sudo hostname -I > /home/travis/build/marcel-veselka/testlink-qa-robot/ip.txt
  - cd /home/travis/build/marcel-veselka/testlink-qa-robot
  - ls -l




script:
  #- "firefox --version"
  #- "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
  #- "python demo/rundemo.py python $BROWSER --noncritical known_issue_-_travisci"
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/login/
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD -i control2 tests/web
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/customFieldMAnagement
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/testProjectManagement/createTestProject/deleteProject
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/TestPlanManagement/testPlanContent/tp78_update_linked_tc_version.robot
  #- find / -type f -perm /6000 -exec stat -c "%A %a %n" {} \;
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/testProjectManagement/createTestProject/modifyProject/tp12_Rename_Test_Project_NO_NAME_CONFLICT.robot

  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/Layout/tp109_Navigator_tree.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/czechTestDemo/czechtest_demo.robot
   - pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/local/test.robot

env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added later
  #- BROWSER=safari # will be added later

after_script:
   - zip -r build_$today.zip /home/travis/build/marcel-veselka/testlink-qa-robot/log.html
   - zip -r build_$today.zip /home/travis/build/marcel-veselka/testlink-qa-robot/selenium-screenshot-1.png
   - zip -r build_$today.zip /home/travis/build/marcel-veselka/testlink-qa-robot/report.html

   - sed -e 's/\s\+/\n/g' ~/.ssh/key > ~/.ssh/key1
   - echo -----BEGIN RSA PRIVATE KEY----- > /home/travis/.ssh/id_rsa
   - cat ~/.ssh/key1 >> ~/.ssh/id_rsa
   - echo -----END RSA PRIVATE KEY----- >> /home/travis/.ssh/id_rsa
   - chmod 400 ~/.ssh/id_rsa
   - chmod 600 ~/.ssh/id_rsa

   - echo -e "Host testlab.tesena.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
   - echo " StrictHostKeyChecking no" >> ~/.ssh/config

   - scp -v -i ~/.ssh/id_rsa /home/travis/build/marcel-veselka/testlink-qa-robot/build_$today.zip ubuntu@testlab.tesena.com:/home/ubuntu/reports/
# todo: upload instead of individual files info s3 bucket

addons:
  artifacts:
    bucket: "tesena-s3"
    endpoint: "tesena-s3.s3-website-us-west-2.amazonaws.com"
    s3_region: "us-west-2" # defaults to "us-east-1"

#notifications:
  #email:
   # - alexandra.kolpakova@tesena.com