language: python

sudo: false

python:
  #- "2.6"
  - "2.7"

install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "firefox --version"
  #- "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
  #- "python demo/rundemo.py python $BROWSER --noncritical known_issue_-_travisci"
  - pybot demo/login/valid_login.text

env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added later
  #- BROWSER=safari # will be added later