language: python

sudo: false

python:
  - "2.7"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  #- gem install s3
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "firefox --version"
  #- "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
  #- "python demo/rundemo.py python $BROWSER --noncritical known_issue_-_travisci"
  #- pybot demo/login/valid_login.txt
  - pybot -v BROWSER:$BROWSER tests/web/login/ -v "VALID USER":$TL_USER

env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added later
  #- BROWSER=safari # will be added later

after_script: zip -r build.zip /home/travis/build/marcel-veselka/testlink-qa-robot/*
# todo: upload instead of individual files info s3 bucket

addons:
  artifacts:
    bucket: "tesena-s3"
    endpoint: "tesena-s3.s3-website-us-west-2.amazonaws.com"
    s3_region: "us-west-2" # defaults to "us-east-1"